FROM golang:1.8.3-alpine3.6
COPY . /go/src/github.com/cdyue/go-shadowsocks2/
COPY ./vendor/ /go/src/
WORKDIR /go/src/github.com/cdyue/go-shadowsocks2/
RUN go build -o app .


FROM alpine:3.6
WORKDIR /root/
COPY --from=0 /go/src/github.com/cdyue/go-shadowsocks2/app .
ENTRYPOINT ["./app"]
